# Generated by Django 5.2.8 on 2026-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Phone', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=120)),
                ('Type', models.TextField()),
                ('Status', models.TextField()),
            ],
        ),
    ]
