# Generated by Django 5.2.8 on 2026-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='Location',
            field=models.CharField(blank='True', max_length=120, null='True'),
        ),
    ]
